### ISSUE TITLE
Why are the new prebuilt binaries encrypted?

### ISSUE THREAD

**Issue by GrimStride** [Sysca11/BedrockX#2]
I'm currently using this tool on my server and it's awesome, but for some reason the new releases are encrypted. I really want to test the new features on my server.
Also wanted to ask for build instructions, i just started on Visual Studio stuff.

**Comment by Sysca11** [comment]
because I turn on some aggressive optimization on new prebuilt-binaries.And without enough unit tests,I'm not sure about its stability(I'm afraid that it will lead to data corruption).I can send you password in telegram.

**Comment by GrimStride** [comment]
Ok, https://t.me/GrimStride

**Comment by Sysca11** [comment]
0414 uploaded,but have issues with /map
