### ISSUE TITLE
没有bdx 0425的源码

### ISSUE THREAD

**Issue by mclk623** [Sysca11/BedrockX#8]
没有bdx 0425的源码，我需要他

**Comment by SeaIce233** [comment]
被删除了

**Comment by Sysca11** [comment]
@SeaIce233 求恁能不能不要对着忘记make archived的repo的已经被owner自己close的issue无限黑屁了。latest commit被你颅内虚无了？
您是用您被PCA降维的脑回路来审视的github源码？
wiki打完编辑战，又来github拉屎，您真是最无聊的人。

**Comment by SeaIce233** [comment]
> @SeaIce233 求恁能不能不要对着忘记make archived的repo的已经被owner自己close的issue无限黑屁了。latest commit被你颅内虚无了？
> 您是用您被PCA降维的脑回路来审视的github源码？
> wiki打完编辑战，又来github拉屎，您真是最无聊的人。

对不起。。。我不懂。。。我还是不说话了吧。。。
